### ISSUE TITLE
analysis_server crash

### ISSUE THREAD

**Issue by DanOlds** [xpdAcq/xpdAcq#565]
Upon trying to use analysis_server in recently deployed environment.  Might be related to run-router? 

```(/opt/conda_envs/collection-2020-2.0rc8-xpdacq) xf28id1@xf28id1-ws2:/$ analysis_server
/opt/conda_envs/collection-2020-2.0rc8-xpdacq/lib/python3.7/site-packages/tomopy/recon/acceleration.py:57: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
{}
/opt/conda_envs/collection-2020-2.0rc8-xpdacq/lib/python3.7/site-packages/xpdan/vend/callbacks/zmq.py:241: DeprecationWarning: ZMQEventLoop and zmq.asyncio.install are deprecated in pyzmq 17. Special eventloop integration is no longer needed.
  loop = zmq_asyncio.ZMQEventLoop()
/opt/conda_envs/collection-2020-2.0rc8-xpdacq/lib/python3.7/site-packages/bluesky/utils.py:901: UserWarning: bluesky.utils.install_qt_kicker is no longer necessary and has no effect. Please remove your use of it. It may be removed in a future release of bluesky.
  warnings.warn("bluesky.utils.install_qt_kicker is no longer necessary and "
Starting Analysis Server
analyzing as diffraction
START ANALYSIS ON 5038af3c-0715-4de8-b86a-29aaf36c80e0
FINISH ANALYSIS ON 5038af3c-0715-4de8-b86a-29aaf36c80e0
Average Event analysis time 0.0
Analysis time 5.019351959228516
analyzing as diffraction
Exception in callback Dispatcher.process(<DocumentNames.start: 'start'>, {'analysis_stage': 'raw', 'beamline_config': {'Verification time': '2020-09-15 14:32:26', 'Verified by': 'gb'}, 'beamline_id': '28-ID-1', 'bt_experimenters': ['Olds'], ...})
handle: <Handle Dispatcher.process(<DocumentNames.start: 'start'>, {'analysis_stage': 'raw', 'beamline_config': {'Verification time': '2020-09-15 14:32:26', 'Verified by': 'gb'}, 'beamline_id': '28-ID-1', 'bt_experimenters': ['Olds'], ...})>
Traceback (most recent call last):
  File "/opt/conda_envs/collection-2020-2.0rc8-xpdacq/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/conda_envs/collection-2020-2.0rc8-xpdacq/lib/python3.7/site-packages/bluesky/run_engine.py", line 2292, in process
    exceptions = self.cb_registry.process(name, name.name, doc)
  File "/opt/conda_envs/collection-2020-2.0rc8-xpdacq/lib/python3.7/site-packages/bluesky/utils.py", line 364, in process
    func(*args, **kwargs)
  File "/opt/conda_envs/collection-2020-2.0rc8-xpdacq/lib/python3.7/site-packages/bluesky/utils.py", line 453, in __call__
    return mtd(*args, **kwargs)
  File "/opt/conda_envs/collection-2020-2.0rc8-xpdacq/lib/python3.7/site-packages/xpdan/vend/callbacks/core.py", line 67, in __call__
    ret = getattr(self, name)(doc)
  File "/opt/conda_envs/collection-2020-2.0rc8-xpdacq/lib/python3.7/site-packages/xpdan/vend/callbacks/core.py", line 533, in start
    cb("start", doc)
  File "/opt/conda_envs/collection-2020-2.0rc8-xpdacq/lib/python3.7/site-packages/xpdan/startup/analysis_server.py", line 158, in <lambda>
    return lambda *x: xrd_namespace["raw_source"].emit(x)
  File "/opt/conda_envs/collection-2020-2.0rc8-xpdacq/lib/python3.7/site-packages/rapidz/core.py", line 397, in emit
    result = self._emit(x)
  File "/opt/conda_envs/collection-2020-2.0rc8-xpdacq/lib/python3.7/site-packages/rapidz/core.py", line 378, in _emit
    r = downstream.update(x, who=self)
  File "/opt/conda_envs/collection-2020-2.0rc8-xpdacq/lib/python3.7/site-packages/rapidz/core.py", line 1144, in update
    return self._emit(tup)
  File "/opt/conda_envs/collection-2020-2.0rc8-xpdacq/lib/python3.7/site-packages/rapidz/core.py", line 378, in _emit
    r = downstream.update(x, who=self)
  File "/opt/conda_envs/collection-2020-2.0rc8-xpdacq/lib/python3.7/site-packages/rapidz/core.py", line 741, in update
    return self._emit(x)
  File "/opt/conda_envs/collection-2020-2.0rc8-xpdacq/lib/python3.7/site-packages/rapidz/core.py", line 378, in _emit
    r = downstream.update(x, who=self)
  File "/opt/conda_envs/collection-2020-2.0rc8-xpdacq/lib/python3.7/site-packages/rapidz/core.py", line 1296, in update
    return self._emit(x[self.pick])
  File "/opt/conda_envs/collection-2020-2.0rc8-xpdacq/lib/python3.7/site-packages/rapidz/core.py", line 378, in _emit
    r = downstream.update(x, who=self)
  File "/opt/conda_envs/collection-2020-2.0rc8-xpdacq/lib/python3.7/site-packages/rapidz/core.py", line 701, in update
    return self._emit(result)
  File "/opt/conda_envs/collection-2020-2.0rc8-xpdacq/lib/python3.7/site-packages/rapidz/core.py", line 378, in _emit
    r = downstream.update(x, who=self)
  File "/opt/conda_envs/collection-2020-2.0rc8-xpdacq/lib/python3.7/site-packages/rapidz/core.py", line 741, in update
    return self._emit(x)
  File "/opt/conda_envs/collection-2020-2.0rc8-xpdacq/lib/python3.7/site-packages/rapidz/core.py", line 378, in _emit
    r = downstream.update(x, who=self)
  File "/opt/conda_envs/collection-2020-2.0rc8-xpdacq/lib/python3.7/site-packages/shed/simple.py", line 697, in update
    return self.emit(inner)
  File "/opt/conda_envs/collection-2020-2.0rc8-xpdacq/lib/python3.7/site-packages/rapidz/core.py", line 397, in emit
    result = self._emit(x)
  File "/opt/conda_envs/collection-2020-2.0rc8-xpdacq/lib/python3.7/site-packages/rapidz/core.py", line 378, in _emit
    r = downstream.update(x, who=self)
  File "/opt/conda_envs/collection-2020-2.0rc8-xpdacq/lib/python3.7/site-packages/rapidz/core.py", line 653, in update
    return self._emit(result)
  File "/opt/conda_envs/collection-2020-2.0rc8-xpdacq/lib/python3.7/site-packages/rapidz/core.py", line 378, in _emit
    r = downstream.update(x, who=self)
  File "/opt/conda_envs/collection-2020-2.0rc8-xpdacq/lib/python3.7/site-packages/rapidz/core.py", line 740, in update
    if self.predicate(x, *self.args, **self.kwargs):
  File "/opt/conda_envs/collection-2020-2.0rc8-xpdacq/lib/python3.7/site-packages/xpdan/pipelines/main.py", line 188, in <lambda>
    fg_dark_query.filter(lambda x: x == []).sink(
  File "/opt/conda_envs/collection-2020-2.0rc8-xpdacq/lib/python3.7/site-packages/databroker/v1.py", line 1019, in __eq__
    return self.start == other.start
AttributeError: 'list' object has no attribute 'start'
```

**Comment by st3107** [comment]
Move to https://github.com/xpdAcq/xpdAn/issues/282
